<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <DebugType>embedded</DebugType>

    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);_references/**;tests/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.png" LogicalName="LoupixDeck.Plugin.PowerToys.icon.png" />
    <EmbeddedResource Include="Assets/Mdi/*.png" LogicalName="LoupixDeck.Plugin.PowerToys.Assets.Mdi.%(Filename)%(Extension)" />
    <None Update="icon.png" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="LoupixDeck.PluginSdk" Version="1.26.0">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
